# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfm < Formula
  desc "Standalone single-binary dotfiles manager"
  homepage "https://github.com/bitcldr/dfm"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitcldr/dfm/releases/download/v0.1.4/dfm_v0.1.4_macos_x86_64.tar.gz"
      sha256 "58aa054787f412b7fd16574299a745dbe8be51c6d2191cf234398bcd7dfae69b"

      define_method(:install) do
        bin.install "dfm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitcldr/dfm/releases/download/v0.1.4/dfm_v0.1.4_macos_arm64.tar.gz"
      sha256 "aa9235c63c1d1aa63f71ed79ff01affb8dbfc03f2055416b5b3514b1bb29a29e"

      define_method(:install) do
        bin.install "dfm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcldr/dfm/releases/download/v0.1.4/dfm_v0.1.4_linux_x86_64.tar.gz"
      sha256 "c60debc408d1efd4c8bc75f6df069cffb7787d61d40fef397c728b0c6be919c6"
      define_method(:install) do
        bin.install "dfm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitcldr/dfm/releases/download/v0.1.4/dfm_v0.1.4_linux_arm64.tar.gz"
      sha256 "ab04a1871ac6e3c69e990dd092b268dd781c3fbacce042792c3efbf32df5e74a"
      define_method(:install) do
        bin.install "dfm"
      end
    end
  end

  test do
    system "#{bin}/dfm", "--help"
  end
end
